version: '2.4'

x-images:
  - &dap-base           DAP_IMAGE

networks:
  dap-network:
    external: DOCKER_NETWORK_EXTERNAL
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24

services:

  signing-service:
    image: *dap-base
    networks:
      - dap-network
    ports:
      - "${SIGNING_SERVICE_SSH_PORT}:22"
      - "${SIGNING_SERVICE_PORT}:${SIGNING_SERVICE_PORT}"
    environment:
      ZHSM: ${ZHSM}
      ZHSM_CREDENTIAL: ${ZHSM_CREDENTIAL}
      SSH_PUBKEY: ${SSH_PUBKEY}
      DAP_SERVICE: SS
      ARGON2_SALT: ${ARGON2_SALT}
      DEPLOY_TIME_SECRET: ${DEPLOY_TIME_SECRET}
      OLD_DEPLOY_TIME_SECRET: ${OLD_DEPLOY_TIME_SECRET}
      DAP_REBOOT: ${DAP_REBOOT}
      ENC_COS_API_KEY: ${ENC_COS_API_KEY}
      ENC_COS_ID: ${ENC_COS_ID}
      ENC_HPCS_API_KEY: ${ENC_HPCS_API_KEY}
      ENC_HPCS_ENDPOINT: ${ENC_HPCS_ENDPOINT}
      ENC_HPCS_GUID: ${ENC_HPCS_GUID}
      ENC_HPCS_ADDRESS: ${ENC_HPCS_ADDRESS}
      ENC_HPCS_CLIENT_KEY_AES_ENC_KEY: ${ENC_HPCS_CLIENT_KEY_AES_ENC_KEY}
      ENC_HPCS_CLIENT_KEY1: ${ENC_HPCS_CLIENT_KEY1}
      ENC_HPCS_CLIENT_KEY2: ${ENC_HPCS_CLIENT_KEY2}
      ENC_HPCS_CLIENT_CERT_AES_ENC_KEY: ${ENC_HPCS_CLIENT_CERT_AES_ENC_KEY}
      ENC_HPCS_CLIENT_CERT: ${ENC_HPCS_CLIENT_CERT}
      DAP_BACKUP_BUCKET: ${DAP_BACKUP_BUCKET}
      WALLET_BACKUP_BUCKET: ${WALLET_BACKUP_BUCKET}
      SKIP_HPCS_VERIFY: ${SKIP_HPCS_VERIFY}
      HPCS_INTERVAL: ${HPCS_INTERVAL}
      RHSSO_HOST: ${RHSSO_HOST}
      DAP_HOST: ${DAP_HOST}
      LOGDNA_INGESTION_KEY: ${LOGDNA_INGESTION_KEY}
      LOGDNA_INGESTION_HOSTNAME: ${LOGDNA_INGESTION_HOSTNAME}
      LOGDNA_API_HOSTNAME: ${LOGDNA_API_HOSTNAME}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      RHSSO_ADMIN_PASSWORD: ${RHSSO_ADMIN_PASSWORD}
      RHPAM_ADMIN_PASSWORD: ${RHPAM_ADMIN_PASSWORD}
      RHPAM_USER_PASSWORD: ${RHPAM_USER_PASSWORD}
      RHPAM_APPROVER_PASSWORD: ${RHPAM_APPROVER_PASSWORD}
      SIGNING_SERVICE_SERVER: ${SIGNING_SERVICE_SERVER}
      TXQUEUE_HOST: ${TXQUEUE_HOST}
      TXQUEUE_PORT: ${TXQUEUE_PORT}
      TXQUEUE_CERT_DIR: /txqueue-cert
      WALLETDB_HOST: ${WALLETDB_HOST}
      WALLETDB_PORT: ${WALLETDB_PORT}
      WALLETDB_CERT_DIR: /walletdb-cert
 